server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/syuho
    schema: syuho
    username: syuho
    password: pass_1234
    driver-class-name: com.mysql.jdbc.Driver
  
doma:
  dialect: MYSQL

---
server:
  port: 8081
spring:
  profiles: heroku
  datasource:
    url: jdbc:mysql://127.0.0.1/syuho
    schema: syuho
    username: syuho
    password: pass_1234
    driver-class-name: org.postgresql.Driver
  
doma:
  dialect: postgres
